[package]
name = "clocks"
version = "0.1.0"
edition = "2021"

[lib]
name = "clocks"
path = "src/lib.rs"

[dependencies]

# replace with windows-sys
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["profileapi"] }